### PR TITLE
#157 implement custom endpoints for Kinesis and DynamoDB

### PR DESCRIPTION
**Pull request by ZAYEC77**
Add config properties:
- `customEndpoint` - to configure access to Kinesis endpoint
- `dynamodbCustomEndpoint` - to configure access to DynamoDB endpoint

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by ZAYEC77** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @ZAYEC77 has signed the Contributor License Agreement. Thanks so much.

**Comment by benjben** [comment]
Handled by #171

**Pull request closed without merging**
